# Generated by Django 5.0.4 on 2024-05-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='counseling_schedule',
            fields=[
                ('counselingID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('counselor_teacher', models.CharField(choices=[('teacher 1', 'Teacher 1'), ('teacher 2', 'Teacher 2'), ('teacher 3', 'Teacher 3'), ('teacher 4', 'Teacher 4')], max_length=255)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
