# Generated by Django 5.0.4 on 2024-05-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseling_schedule',
            name='scheduled_date',
            field=models.DateField(),
        ),
    ]
