# Generated by Django 5.0.4 on 2024-05-23 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtassessment',
            name='dateAccepted',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 11, 25, 42, 611201, tzinfo=datetime.timezone.utc)),
        ),
    ]
