# Generated by Django 5.0.4 on 2024-05-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0002_alter_counseling_schedule_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseling_schedule',
            name='scheduled_time',
            field=models.CharField(choices=[('8-9', '8:00 AM - 9:00 AM'), ('9-10', '9:00 AM - 10:00 AM'), ('10-11', '10:00 AM-11:00 AM'), ('11-12', '11:00 AM -12:00 PM'), ('1-2', '1:00 PM - 2:00 PM'), ('2-3', '2:00 PM - 3:00 PM'), ('3-4', '3:00 PM - 4:00 PM'), ('4-5', '4:00 PM - 5:00 PM')], max_length=15),
        ),
    ]
