# Generated by Django 5.0.4 on 2024-05-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0002_counseling_schedule_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counseling_schedule',
            old_name='scheduled_date',
            new_name='scheduled_datetime',
        ),
        migrations.RemoveField(
            model_name='counseling_schedule',
            name='scheduled_time',
        ),
    ]
