# Generated by Django 5.0.4 on 2024-05-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0003_rename_scheduled_date_counseling_schedule_scheduled_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseling_schedule',
            name='scheduled_datetime',
            field=models.DateTimeField(),
        ),
    ]
