# Generated by Django 5.0.4 on 2024-05-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0003_alter_counseling_schedule_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='counseling_schedule',
            name='email',
            field=models.EmailField(default='bryanantier7@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
