# Generated by Django 5.0.4 on 2024-05-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0004_counseling_schedule_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseling_schedule',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
