# Generated by Django 5.0.4 on 2024-06-01 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0004_exit_interview_db_majorevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprofilebasicinfo',
            name='familyName',
        ),
        migrations.RemoveField(
            model_name='individualprofilebasicinfo',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='individualprofilebasicinfo',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='individualprofilebasicinfo',
            name='sex',
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAO_WebApp.studentinfo'),
        ),
        migrations.AlterField(
            model_name='ojtassessment',
            name='dateAccepted',
            field=models.DateField(),
        ),
    ]
