# Generated by Django 5.0.4 on 2024-06-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0005_remove_individualprofilebasicinfo_familyname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualprofilebasicinfo',
            old_name='courseyearsection',
            new_name='section',
        ),
        migrations.AddField(
            model_name='individualprofilebasicinfo',
            name='yearlvl',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
