# Generated by Django 5.0.4 on 2024-05-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0005_individualprofilebasicinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofilebasicinfo',
            name='sexualOrientationOther',
            field=models.CharField(default='idk', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='specifyScholarship',
            field=models.CharField(default='parents', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='typeOfScholarship',
            field=models.CharField(choices=[('private', ' Scholarship by private institution'), ('government', 'Government Scholarship'), ('organizations', ' Scholarships granted by organizations within CTU')], max_length=100),
        ),
    ]
