# Generated by Django 5.0.4 on 2024-05-21 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0005_alter_counseling_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseling_schedule',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAO_WebApp.studentinfo'),
        ),
    ]
