# Generated by Django 5.0.4 on 2024-06-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0006_rename_courseyearsection_individualprofilebasicinfo_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualprofilebasicinfo',
            old_name='livingWithOthers',
            new_name='livingSpecify',
        ),
        migrations.RemoveField(
            model_name='individualprofilebasicinfo',
            name='livingWithRelative',
        ),
    ]
