# Generated by Django 5.0.4 on 2024-05-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0007_individualprofilebasicinfo_fatherctu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprofilebasicinfo',
            name='sexualOrientationOther',
        ),
    ]
