# Generated by Django 5.0.4 on 2024-06-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0007_rename_livingwithothers_individualprofilebasicinfo_livingspecify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='curriculumtype',
            field=models.CharField(choices=[('oldsecondary', 'Old Secondary Curriculum Graduate'), ('seniorhigh', 'Senior High School Graduate')], max_length=50),
        ),
    ]
