# Generated by Django 5.0.4 on 2024-06-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0008_alter_individualprofilebasicinfo_curriculumtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualprofilebasicinfo',
            old_name='sourceOfIncomeFamilyBusiness',
            new_name='sourceOfIncomeSpecify',
        ),
        migrations.RemoveField(
            model_name='individualprofilebasicinfo',
            name='sourceOfIncomeRelative',
        ),
    ]
