# Generated by Django 5.0.4 on 2024-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0009_testarray'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='curriculumtype',
            field=models.CharField(choices=[('oldsecondary', 'Old Secondary Curriculum Graduate'), ('seniorhigh', 'Senior High School Graduate')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='fatherOtherOccupation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='livingWithOthers',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='livingWithRelative',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='motherOtherOccupation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='placeOfLivingOthers',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='sourceOfIncomeFamilyBusiness',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='sourceOfIncomeRelative',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='specifyScholarship',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='track',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='typeOfScholarship',
            field=models.CharField(choices=[('private', ' Scholarship by private institution'), ('government', 'Government Scholarship'), ('organizations', ' Scholarships granted by organizations within CTU')], default='', max_length=100),
        ),
    ]
