# Generated by Django 5.0.4 on 2024-05-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0009_alter_individualprofilebasicinfo_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='studentId',
            field=models.IntegerField(),
        ),
    ]
