# Generated by Django 5.0.4 on 2024-06-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0009_rename_sourceofincomefamilybusiness_individualprofilebasicinfo_sourceofincomespecify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='typeOfScholarship',
            field=models.CharField(choices=[('private', ' Scholarship by private institution'), ('government', 'Government Scholarship'), ('organizations', ' Scholarships granted by organizations within CTU')], max_length=100),
        ),
    ]
