# Generated by Django 5.0.4 on 2024-05-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0011_alter_individualprofilebasicinfo_studentphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='studentPhoto',
            field=models.FileField(upload_to='media/studentPhoto'),
        ),
    ]
