# Generated by Django 5.0.4 on 2024-05-22 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0012_alter_individualprofilebasicinfo_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='exit_interview_db',
            fields=[
                ('exitinterviewId', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('dateEnrolled', models.DateField()),
                ('reasonForLeaving', models.CharField(max_length=255)),
                ('satisfiedWithAcadamic', models.BooleanField(default=False)),
                ('feedbackWithAcademic', models.CharField(max_length=255)),
                ('satisfiedWithSocial', models.BooleanField(default=False)),
                ('feedbackWithSocial', models.CharField(max_length=255)),
                ('satisfiedWithServices', models.BooleanField(default=False)),
                ('feedbackWithServices', models.CharField(max_length=255)),
                ('contributedToDecision', models.JSONField()),
                ('intendedMajor', models.CharField(max_length=255)),
                ('firstConsider', models.CharField(max_length=255)),
                ('whatCondition', models.CharField(max_length=255)),
                ('recommend', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('howSatisfied', models.CharField(choices=[('very satisfied', 'Very satisfied'), ('somewhat satisfied', 'Somewhat satisfied'), ('satisfied', 'Satisfied'), ('somewhat dissatisfied', 'Somewhat Dissatisfied'), ('very dissatisfied', 'Very Dissatisfied')], max_length=30)),
                ('planTOReturn', models.CharField(max_length=255)),
                ('accademicExperienceSatisfied', models.BooleanField(default=False)),
                ('knowAboutYourTime', models.CharField(max_length=255)),
                ('currentlyEmployed', models.BooleanField(default=False)),
                ('ifYesEmployed', models.CharField(max_length=255)),
                ('ifNoEmployed', models.CharField(max_length=255)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAO_WebApp.studentinfo')),
            ],
        ),
    ]
