# Generated by Django 5.0.4 on 2024-05-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0013_individualprofilebasicinfo_describeyoubestother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='describeYouBestOther',
            field=models.CharField(default='', max_length=255),
        ),
    ]
