# Generated by Django 5.0.4 on 2024-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0013_exit_interview_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exit_interview_db',
            old_name='ifNoEmployed',
            new_name='explainationEmployed',
        ),
        migrations.RemoveField(
            model_name='exit_interview_db',
            name='ifYesEmployed',
        ),
        migrations.AlterField(
            model_name='exit_interview_db',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
