# Generated by Django 5.0.4 on 2024-05-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0014_rename_ifnoemployed_exit_interview_db_explainationemployed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit_interview_db',
            name='exitinterviewId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
