# Generated by Django 5.0.4 on 2024-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0014_alter_individualprofilebasicinfo_describeyoubestother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='finaciallySupporting',
            field=models.CharField(choices=[('parents', 'Parents'), ('spouse', 'Spouse'), ('relatives', 'Relatives'), ('selfsupporting', 'Self-supporting'), ('scholarship', 'Scholarship')], max_length=20),
        ),
    ]
