# Generated by Django 5.0.4 on 2024-05-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0015_alter_individualprofilebasicinfo_finaciallysupporting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='bloodType',
            field=models.CharField(choices=[('O-', 'O negative'), ('O+', 'O positive'), ('A-', 'A negative'), ('A+', 'A positive'), ('B-', 'B negative'), ('B+', 'B possitive'), ('AB-', 'AB negative'), ('AB+', 'AB positive')], max_length=10),
        ),
    ]
