# Generated by Django 5.0.4 on 2024-05-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0015_alter_exit_interview_db_exitinterviewid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OjtAssessment',
            fields=[
                ('OjtRequestID', models.AutoField(primary_key=True, serialize=False)),
                ('schoolYear', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033'), ('2033-2034', '2033-2034'), ('2034-2035', '2034-2035'), ('2035-2036', '2035-2036'), ('2036-2037', '2036-2037'), ('2037-2038', '2037-2038'), ('2038-2039', '2038-2039'), ('2039-2040', '2039-2040'), ('2040-2041', '2040-2041')], max_length=10)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAO_WebApp.studentinfo')),
            ],
        ),
    ]
