# Generated by Django 5.0.4 on 2024-05-22 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0016_ojtassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit_interview_db',
            name='dateRecieved',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 15, 23, 28, 276406, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='ojtassessment',
            name='dateRecieved',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 15, 23, 28, 276406, tzinfo=datetime.timezone.utc)),
        ),
    ]
