# Generated by Django 5.0.4 on 2024-05-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0017_exit_interview_db_daterecieved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit_interview_db',
            name='dateRecieved',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ojtassessment',
            name='dateRecieved',
            field=models.DateField(),
        ),
    ]
