# Generated by Django 5.0.4 on 2024-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAO_WebApp', '0018_alter_exit_interview_db_daterecieved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit_interview_db',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending'), ('Expired', 'Expired')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='ojtassessment',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending'), ('Expired', 'Expired')], default='Pending', max_length=10),
        ),
    ]
